// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD0lZOCNzFGhvaJcpp1a2qRlfZ52RJc2c',
    appId: '1:795487735061:web:585710bc6003595c57ed1c',
    messagingSenderId: '795487735061',
    projectId: 'community-2a3d1',
    authDomain: 'community-2a3d1.firebaseapp.com',
    storageBucket: 'community-2a3d1.firebasestorage.app',
    measurementId: 'G-64WTT7E2J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8MEC0wqol5BSM06rVPMqs4NlIyndtTe0',
    appId: '1:795487735061:android:83817fbb675d3d5d57ed1c',
    messagingSenderId: '795487735061',
    projectId: 'community-2a3d1',
    storageBucket: 'community-2a3d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCesJ28fIyw2U2dn3HzttQN8seqrvhRCws',
    appId: '1:795487735061:ios:e0afb76968247cba57ed1c',
    messagingSenderId: '795487735061',
    projectId: 'community-2a3d1',
    storageBucket: 'community-2a3d1.firebasestorage.app',
    androidClientId: '795487735061-s8p00c05kjqrdr98kfhfrodk5q4jjfc5.apps.googleusercontent.com',
    iosClientId: '795487735061-ctr5mrdeb29ikcqq8q740b8pvj1g82if.apps.googleusercontent.com',
    iosBundleId: 'com.example.community',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCesJ28fIyw2U2dn3HzttQN8seqrvhRCws',
    appId: '1:795487735061:ios:e0afb76968247cba57ed1c',
    messagingSenderId: '795487735061',
    projectId: 'community-2a3d1',
    storageBucket: 'community-2a3d1.firebasestorage.app',
    androidClientId: '795487735061-s8p00c05kjqrdr98kfhfrodk5q4jjfc5.apps.googleusercontent.com',
    iosClientId: '795487735061-ctr5mrdeb29ikcqq8q740b8pvj1g82if.apps.googleusercontent.com',
    iosBundleId: 'com.example.community',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD0lZOCNzFGhvaJcpp1a2qRlfZ52RJc2c',
    appId: '1:795487735061:web:90f54ca509118d7857ed1c',
    messagingSenderId: '795487735061',
    projectId: 'community-2a3d1',
    authDomain: 'community-2a3d1.firebaseapp.com',
    storageBucket: 'community-2a3d1.firebasestorage.app',
    measurementId: 'G-ZGRPLED4TV',
  );
}
